/*
*Auto-generated by: https://github.com/pmndrs/gltfjsx*
*Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)*
*License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)*
*Source: https://sketchfab.com/3d-models/python-8be4a2579dd84586b915068e475073ee*
*Title: Python*
*/
import React, { useCallback, useRef } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

const PythonModel = (props) => {
  // const { nodes, materials } = useGLTF('public/models/scene.gltf')
  const refList = useRef([]);
  const getRef = useCallback((mesh) => {
    if (mesh && !refList.current.includes(mesh)) {
      refList.current.push(mesh);
    }
  }, []);
  const texture = useTexture('textures/python/rings.png');

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Python_Python_0.geometry}
          material={materials.Python}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/python/scene.gltf')

export default PythonModel